### ISSUE TITLE
Travis CI build is failing

### ISSUE THREAD

**Issue by dipanjan** [phil-opp/nightly-libcore#9]
I couldn't build nightly-libcore with rust-1.20.0-nightly. It throws in a bunch of errors.

**Comment by phil-opp** [comment]
Hi, I no longer maintain this crate actively, since most people use [xargo](https://github.com/japaric/xargo) now. The cause of the problem is likely that the auto-update failed because the no-float patch is no longer up-to-date. Do you rely on the `disable_float` feature? Otherwise we could just remove it to fix the build again.

**Comment by dipanjan** [comment]
I am trying to build rust.ko which relies on [disable_float](https://github.com/tsgates/rust.ko/blob/master/Cargo.toml) feature, sadly. How does xargo substitute nightly-libcore?

**Comment by phil-opp** [comment]
It is a wrapper around cargo that automatically builds the `core` library when compiling for a different target. So instead of `cargo build`, you run `xargo build` and everything just works.

To build rust.ko with xargo, you need to remove the override of the core library [from the Cargo.toml](https://github.com/tsgates/rust.ko/blob/a0973d04819b9dba14937d179af0517a1c85100d/Cargo.toml#L8-L10). To disable hardware floats, you can add `+soft-float` to the [features line](https://github.com/tsgates/rust.ko/blob/a0973d04819b9dba14937d179af0517a1c85100d/x86_64-unknown-none-gnu.json#L12) in the target specification file.

Hope this helps!

**Comment by dipanjan** [comment]
Thank you so much. Will give a try.
